# Generated by Django 4.2.3 on 2023-08-02 16:59

from django.db import migrations, models
import pdftospeech.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=pdftospeech.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
