# Generated by Django 4.2.1 on 2023-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IaAudioResponse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('BinaryContent', models.BinaryField()),
                ('StringResponse', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
