# Generated by Django 4.2.1 on 2023-05-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioResponse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iaaudioresponse',
            old_name='BinaryContent',
            new_name='binaryContent',
        ),
        migrations.RenameField(
            model_name='iaaudioresponse',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='iaaudioresponse',
            old_name='StringResponse',
            new_name='stringResponse',
        ),
    ]
