# Generated by Django 4.2.2 on 2023-07-13 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaresponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaresponse',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 13, 40, 54, 219093)),
        ),
    ]
