# Generated by Django 4.2.2 on 2023-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaresponse', '0002_alter_iaresponse_date_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaresponse',
            name='date_register',
        ),
        migrations.AddField(
            model_name='iaresponse',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
