# Generated by Django 4.2.2 on 2023-07-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaresponse', '0003_remove_iaresponse_date_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iaresponse',
            old_name='audio_responses',
            new_name='audio_response',
        ),
    ]
