# Generated by Django 4.2.2 on 2023-07-13 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import iaresponse.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('audio_responses', models.FileField(upload_to=iaresponse.models.get_upload_path)),
                ('date_register', models.DateTimeField(default=datetime.datetime(2023, 7, 13, 13, 34, 29, 664448))),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaresponse.folder')),
            ],
        ),
    ]
